sudo: false
language: cpp

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - clang-3.8

env:
  - COMPILER=g++-9
  - COMPILER=clang++-6.0

script:
  - make CXX=$COMPILER
