language: cpp
os: linux
dist: bionic

addons:
  apt:
    sources:
      - sourceline: "ppa:ubuntu-toolchain-r/ppa"
      - sourceline: "ppa:ubuntu-toolchain-r/test"

    packages:
      - g++-9

env:
  - COMPILER=g++-9

script:
  - make CXX=$COMPILER